language: rust
sudo: false

cache:
  - cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --git https://github.com/rust-lang-nursery/mdBook.git mdbook)
  - cargo install-update -a

script:
  - mdbook build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/
  keep-history: false
  fqdn: balance.tf
  on:
    branch: master
